setup:
  channels: &setup_channels
    - uibcdf
    - conda-forge
    - ambermd
    - defaults
  dependencies: &setup_dependencies
    - python
    - pip
    - setuptools >=61.0
    - versioningit~=2.0

production:
  channels: &production_channels
    - *setup_channels
  dependencies: &production_dependencies
    - *setup_dependencies
    - molsysmt
    - pyunitwizard
    - pint
    - openmm
    - tqdm

test:
  channels: &test_channels
    - *production_channels
  dependencies: &test_dependencies
    - *production_dependencies
    - pytest
    - pip
    - pytest-cov
    - codecov
    - pytest-xdist

docs:
  channels: &docs_channels
    - *production_channels
  dependencies: &docs_dependencies
    - *production_dependencies
    - jupyterlab
    - sphinx
    - pydata-sphinx-theme
    - sphinxcontrib-bibtex
    - sphinx-remove-toctrees
    - sphinx-copybutton
    - sphinx-design
    - sphinx-favicon
    - sphinx-tabs
    - myst-nb
    - seaborn
    - nbsphinx
    - plotly

development:
  channels:
    - *production_channels
  dependencies:
    - *production_dependencies
    - *test_dependencies
    - *docs_dependencies
    - mamba

conda-build:
  channels:
    - *production_channels
  dependencies:
    - anaconda-client
    - conda-build

